name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11-venv python3-pip
          python3.11 -m venv env_cicd
          source env_cicd/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Python server
        run: |
          source env_cicd/bin/activate
          python manage.py runserver 0.0.0.0:8080 > server.log 2>&1 &
          sleep 5
          cat server.log

      - name: Wait for server
        run: npx wait-on http://localhost:8080


      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run
