name: Cypress Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:13.7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Start Python app
        run: |
          python3 manage.py runserver 0.0.0.0:5000 &
      
      - name: Wait for server
        run: npx wait-on http://localhost:5000

      - name: Run Cypress tests
        run: npx cypress run
