name: CI – DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & start app
        run: |
          docker build -t app-under-test .
          docker run -d --name sut -p 8080:8080 app-under-test

      - name: Run OWASP ZAP baseline scan (1 min, JSON)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://host.docker.internal:8080'
          cmd_options: |
            -m 1                      # spider + passive scan for 1 minute
            -J zap_report.json        # write JSON report

      - name: Upload DAST report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.json

      - name: Tear down
        if: always()
        run: |
          docker stop sut
          docker rm sut
