name: CI – DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dast:
    name: DAST scan with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & start application
        run: |
          docker build -t app-under-test .
          docker run -d --name sut -p 8080:8080 app-under-test

      - name: Launch OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'http://host.docker.internal:8080'
          cmd_options: '-t 2 -r zap_report.html'

   
      - name: Upload DAST report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html

      - name: Tear down application
        if: always()
        run: |
          docker stop sut && docker rm sut
