name: CI – DAST Scan

on:
  push:
  workflow_dispatch:          

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & start app
        run: |
          docker build -t app-under-test .
          docker run -d --name sut -p 8080:8080 app-under-test

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'http://host.docker.internal:8080'
          cmd_options: '-t 1 -r zap_report.json'

      - name: Upload DAST report
        uses: 'actions/upload-artifact@v2'
        with:
          name: zap-report
          path: zap_report.json

      - name: Tear down
        if: always()
        run: |
          docker stop sut && docker rm sut
