name: 🧼 Dockerfile Lint

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-lint.yml'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
