name: Trivy Scan

on: [push]

jobs:
  trivy:
    name: Scan Docker image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        continue-on-error: true
        run: |
          IMAGE=futiz/ugocicd:dev-${{ github.sha }}
          echo "Scanning image $IMAGE"
          trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE
